const productos = [
{
        "id" : 1,
        "producto" : "Remera con logo",
        "foto" : ["../asset/remera_blanca_logo.jpg"],
        "color" : "blanca",
        "marca" : "year",
        "talle" : "M",
        "precio" : 2500,
    },
    {
        "id" : 2,
        "producto" : "Remera lisa",
        "foto" : ["../asset/remera_negra(1).jpg"],
        "color" : "blanca",
        "marca": "year",
        "talle" : "L",
        "precio" : 2500,
    },
    {
        "id" : 3,
        "producto" : "Remera con estampa",
        "foto" : ["../asset/remera_naranja.jpg"],
        "color" : "naranja",
        "marca": "squadra5",
        "talle" : "L",
        "precio" : 2600,
    },
    {
        "id" : 4,
        "producto" : "Remera con estampa",
        "foto" : ["../asset/remera_negra3.jpg"],
        "color" : "negro",
        "marca" : "nubia",
        "talle" : "XL",
        "precio" : 2700,
    },
    {
        "id" : 5,
        "producto" : "Remera con estampa",
        "foto" : ["../asset/remera_rosa.jpg"],
        "color" : "rosa",
        "marca" : "fazurri",
        "talle" : "S",
        "precio" : 2500,
    },
    {
        "id" : 6,
        "producto" : "Remera con estampa",
        "foto" : ["../asset/remera_verde.jpg"],
        "color" : "verde",
        "marca" : "squadra5",
        "talle" : "L",
        "precio" : 2600,
    }
]
