const productosOferta = [
    {
        "id" : 1,
        "producto" : "remera",
        "nombre" : "Remera azul con manga negra",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_azul_mangas_negras.jpg"],
        "marca" : "year",
        "talles" : "M",
        "precio" : 5000,
    },
    {
        "id" : 2,
        "producto" : "remera",
        "nombre" : "Remera blanca con detalles",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_blanca_manga_negra.jpg"],
        "marca": "year",
        "talles" : "L",
        "precio" : 5200,
    },
    {
        "id" : 3,
        "producto" : "remera",
        "nombre" : "Remera beige con dibujo",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_oso_beige.jpg"],
        "marca": "squadra5",
        "talles" : "L",
        "precio" : 5600,
    },
    {
        "id" : 4,
        "producto" : "gorra",
        "nombre" : "Gorra blanca",
        "foto" : ["../asset/Productos/Hombres-prod/Gorras/Gorra_blanca.jpg"],
        "marca" : "wilde",
        "talles" : "M",
        "precio" : 4000,
    },
    {
        "id" : 5,
        "producto" : "top",
        "nombre" : "Top blanco con mangas rayadas",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/top_blanco_mangas_rayas.jpg"],
        "marca" : "fazurri",
        "talles" : "S",
        "precio" : 6500,
    },
    {
        "id" : 6,
        "producto" : "calza",
        "nombre" : "calza blanca lisa",
        "foto" : ["../asset/Productos/Mujer-prod/Calzas/Calza_con_pollera_blanca.jpg"],
        "marca" : "squadra5",
        "talles" : "L",
        "precio" : 7500,
    },
    {
        "id" : 7,
        "producto" : "calza",
        "nombre" : "calza negra con detalles",
        "foto" : ["../asset/Productos/Mujer-prod/Calzas/calza_negra_detalles.jpg"],
        "marca" : "squadra5",
        "talles" : "L",
        "precio" : 7600,
    },
    {
        "id" : 8,
        "producto" : "Remera con estampa",
        "nombre" : "Remera dos colores",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/remera_blanca_con_azul.jpg"],
        "marca" : "squadra5",
        "talles" : "L",
        "precio" : 4000,
    }
]
const productosMujer = [
    // BODIES
    {
        "id" : 10,
        "producto" : "Body",
        "nombre" : "Body beige manga larga",
        "foto" : ["../asset/Productos/Mujer-prod/Bodies/Body_beige.jpg"],
        "marca" : "moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 4000,
    },
    {
        "id" : 11,
        "producto" : "Body",
        "nombre" : "Body unica manga blanco",
        "foto" : ["../asset/Productos/Mujer-prod/Bodies/Body_blanco.jpg"],
        "marca" : "moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 4200,
    },
    {
        "id" : 12,
        "producto" : "Body",
        "nombre" : "Body sin manga blanco",
        "foto" : ["../asset/Productos/Mujer-prod/Bodies/Body_blanco_2.jpg"],
        "marca" : "moda Drip",
        "talles" : "xs,s,m,l,xl",
        "precio" : 4400,
    },
    {
        "id" : 13,
        "producto" : "Body",
        "nombre" : "Body manga corta bordo",
        "foto" : ["../asset/Productos/Mujer-prod/Bodies/Body_bordo.jpg"],
        "marca" : "moda Drip",
        "talles" : "xs,s,m,l,xl",   
        "precio" : 4300,
    },
    {
        "id" : 14,
        "producto" : "Body",
        "nombre" : "Body sin mangas naranja",
        "foto" : ["../asset/Productos/Mujer-prod/Bodies/Body_naranja.jpg"],
        "marca" : "moda Drip",
        "talles" : "xs,s,m,l,xl",   
        "precio" : 4000,
    },
    {
        "id" : 15,
        "producto" : "Body",
        "nombre" : "Body unica manga negro",
        "foto" : ["../asset/Productos/Mujer-prod/Bodies/Body_negro.jpg"],
        "marca" : "moda SR",
        "talles" : "xs,s,m,l,xl",   
        "precio" : 4400,
    },
    {
        "id" : 16,
        "producto" : "Body",
        "nombre" : "Body mangas larga negro",
        "foto" : ["../asset/Productos/Mujer-prod/Bodies/Body_negro_manga_larga.jpg"],
        "marca" : "moda SR",
        "talles" : "xs,s,m,l,xl",   
        "precio" : 4600,
    },
    {
        "id" : 17,
        "producto" : "Body",
        "nombre" : "Body manga corta rojo",
        "foto" : ["../asset/Productos/Mujer-prod/Bodies/Body_rojo.jpg"],
        "marca" : "moda Drip",
        "talles" : "xs,s,m,l,xl",   
        "precio" : 4200,
    },
    {
        "id" : 18,
        "producto" : "Body",
        "nombre" : "Body manga larga rojo oscuro",
        "foto" : ["../asset/Productos/Mujer-prod/Bodies/Body_rojo_manga_larga.jpg"],
        "marca" : "moda SR",
        "talles" : "xs,s,m,l,xl",   
        "precio" : 4500,
    },
    {
        "id" : 19,
        "producto" : "Body",
        "nombre" : "Body manga corta verde",
        "foto" : ["../asset/Productos/Mujer-prod/Bodies/Body_verde.jpg"],
        "marca" : "moda Drip",
        "talles" : "xs,s,m,l,xl",   
        "precio" : 4200,
    },
    {
        "id" : 20,
        "producto" : "Body",
        "nombre" : "Body manga larga verde agua",
        "foto" : ["../asset/Productos/Mujer-prod/Bodies/Body_verde_agua.jpg"],
        "marca" : "moda SR",
        "talles" : "xs,s,m,l,xl",   
        "precio" : 4600,
    },
    //BUZOS
    {
        "id" : 21,
        "producto" : "Buzo",
        "nombre" : "Buzo corto blanco",
        "foto" : ["../asset/Productos/Mujer-prod/Buzos/Buzo_blanco.jpg"],
        "marca" : "Paris",
        "talles" : "xs,s,m,l,xl",   
        "precio" : 8200,
    },
    {
        "id" : 22,
        "producto" : "Buzo",
        "nombre" : "Buzo blanco con estampa",
        "foto" : ["../asset/Productos/Mujer-prod/Buzos/Buzo_blanco_2.jpg"],
        "marca" : "Style Drip",
        "talles" : "xs,s,m,l,xl",   
        "precio" : 8000,
    },
    {
        "id" : 23,
        "producto" : "Buzo",
        "nombre" : "Buzo corto con estampa",
        "foto" : ["../asset/Productos/Mujer-prod/Buzos/Buzo_blanco_3.jpg"],
        "marca" : "Love",
        "talles" : "xs,s,m,l,xl",   
        "precio" : 8600,
    },
    {
        "id" : 24,
        "producto" : "Buzo",
        "nombre" : "Buzo 2 colores",
        "foto" : ["../asset/Productos/Mujer-prod/Buzos/Buzo_blanco_negro.jpg"],
        "marca" : "Style Drip",
        "talles" : "xs,s,m,l,xl",   
        "precio" : 9600,
    },
    {
        "id" : 25,
        "producto" : "Buzo",
        "nombre" : "Buzo corto estampado",
        "foto" : ["../asset/Productos/Mujer-prod/Buzos/Buzo_corto_blanco_azul.jpg"],
        "marca" : "Style Drip",
        "talles" : "xs,s,m,l,xl",   
        "precio" : 9000,
    },
    {
        "id" : 26,
        "producto" : "Buzo",
        "nombre" : "Buzo degradado",
        "foto" : ["../asset/Productos/Mujer-prod/Buzos/Buzo_degrade_blanco_azul.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",   
        "precio" : 8000,
    },
    {
        "id" : 27,
        "producto" : "Buzo",
        "nombre" : "Buzo 2 colores",
        "foto" : ["../asset/Productos/Mujer-prod/Buzos/Buzo_gris_mangas_blanca.jpg"],
        "marca" : "Style drip",
        "talles" : "xs,s,m,l,xl",   
        "precio" : 9000,
    },
    {
        "id" : 28,
        "producto" : "Buzo",
        "nombre" : "Buzo gris oscuro",
        "foto" : ["../asset/Productos/Mujer-prod/Buzos/Buzo_gris_oscuro.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",   
        "precio" : 9000,
    },
    {
        "id" : 29,
        "producto" : "Buzo",
        "nombre" : "Buzo polar",
        "foto" : ["../asset/Productos/Mujer-prod/Buzos/Buzo_gris_polar.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",   
        "precio" : 10000,
    },
    {
        "id" : 30,
        "producto" : "Buzo",
        "nombre" : "Buzo corto negro",
        "foto" : ["../asset/Productos/Mujer-prod/Buzos/Buzo_negro.jpg"],
        "marca" : "Paris",
        "talles" : "xs,s,m,l,xl",   
        "precio" : 8600,
    },
    {
        "id" : 31,
        "producto" : "Buzo",
        "nombre" : "Buzo 3 colores",
        "foto" : ["../asset/Productos/Mujer-prod/Buzos/Buzo_negro_bordo_blanco.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",   
        "precio" : 9000,
    },
    {
        "id" : 32,
        "producto" : "Buzo",
        "nombre" : "Buzo 3 colores",
        "foto" : ["../asset/Productos/Mujer-prod/Buzos/Buzo_negro_rosa.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",   
        "precio" : 9000,
    },
    {
        "id" : 33,
        "producto" : "Buzo",
        "nombre" : "Buzo estampado",
        "foto" : ["../asset/Productos/Mujer-prod/Buzos/Buzo_oso.jpg"],
        "marca" : "Style Drip",
        "talles" : "xs,s,m,l,xl",   
        "precio" : 10000,
    },
    // CALZAS
    {
        "id" : 34,
        "producto" : "Calza",
        "nombre" : "Calza bordo",
        "foto" : ["../asset/Productos/Mujer-prod/Calzas/Calza_bordo.jpg"],
        "marca" : "Vera Cruz",
        "talles" : "xs,s,m,l,xl",
        "precio" : 7000,
    },
    {
        "id" : 35,
        "producto" : "Calza",
        "nombre" : "Calza negra",
        "foto" : ["../asset/Productos/Mujer-prod/Calzas/Calza_negra.jpg"],
        "marca" : "Vera Cruz",
        "talles" : "xs,s,m,l,xl",
        "precio" : 7000,
    },
    {
        "id" : 36,
        "producto" : "Calza",
        "nombre" : "Calza con pollera",
        "foto" : ["../asset/Productos/Mujer-prod/Calzas/Calza_con_pollera_blanca.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 8000,
    },
    {
        "id" : 37,
        "producto" : "Calza",
        "nombre" : "Calza con pollera",
        "foto" : ["../asset/Productos/Mujer-prod/Calzas/Calza_con_pollera_celeste.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 8000,
    },
    {
        "id" : 38,
        "producto" : "Calza",
        "nombre" : "Calza con pollera",
        "foto" : ["../asset/Productos/Mujer-prod/Calzas/Calza_con_pollera_gris.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 8200,
    },
    {
        "id" : 39,
        "producto" : "Calza",
        "nombre" : "Calza con pollera",
        "foto" : ["../asset/Productos/Mujer-prod/Calzas/Calza_con_pollera_roja.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 8000,
    },
    {
        "id" : 40,
        "producto" : "Calza",
        "nombre" : "Calza estampada",
        "foto" : ["../asset/Productos/Mujer-prod/Calzas/Calza_detalles_transparente.jpg"],
        "marca" : "Style Drip",
        "talles" : "xs,s,m,l,xl",
        "precio" : 10000,
    },
    {
        "id" : 41,
        "producto" : "Calza",
        "nombre" : "Calza detalles transparentes",
        "foto" : ["../asset/Productos/Mujer-prod/Calzas/Calza_negra_detalles.jpg"],
        "marca" : "Style Drip",
        "talles" : "xs,s,m,l,xl",
        "precio" : 9400,
    },
    {
        "id" : 42,
        "producto" : "Calza",
        "nombre" : "Calza detalles transparentes",
        "foto" : ["../asset/Productos/Mujer-prod/Calzas/Calza_negra_detalles_transparente.jpg"],
        "marca" : "Style Drip",
        "talles" : "xs,s,m,l,xl",
        "precio" : 9600,
    },
    {
        "id" : 43,
        "producto" : "Calza",
        "nombre" : "Calza lisa",
        "foto" : ["../asset/Productos/Mujer-prod/Calzas/Calza_rosa.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 8000,
    },
    {
        "id" : 44,
        "producto" : "Calza",
        "nombre" : "Calza lisa",
        "foto" : ["../asset/Productos/Mujer-prod/Calzas/Calza_verde.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 8000,
    },
    {
        "id" : 45,
        "producto" : "Calza",
        "nombre" : "Calza camuflada",
        "foto" : ["../asset/Productos/Mujer-prod/Calzas/Calza_verde_camuflada.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 10000,
    },
    // REMERAS
    {
        "id" : 46,
        "producto" : "Remera",
        "nombre" : "Blusa blanca",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Blusa_blanca.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 5000,
    },
    {
        "id" : 47,
        "producto" : "Remera",
        "nombre" : "Blusa gris",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Blusa_gris.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 5000,
    },
    {
        "id" : 48,
        "producto" : "Remera",
        "nombre" : "Blusa roja",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Blusa_roja.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 5000,
    },
    {
        "id" : 49,
        "producto" : "Remera",
        "nombre" : "Blusa verde",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Blusa_verde.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 5000,
    },
    {
        "id" : 50,
        "producto" : "Remera",
        "nombre" : "Remera 3 colores",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Remera_azul_rosa_blanca.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 5300,
    },
    {
        "id" : 51,
        "producto" : "Remera",
        "nombre" : "Remera lisa",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Remera_beige.jpg"],
        "marca" : "Paris",
        "talles" : "xs,s,m,l,xl",
        "precio" : 5100,
    },
    {
        "id" : 52,
        "producto" : "Remera",
        "nombre" : "Remera 2 colores",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Remera_blanca_con_azul.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 5300,
    },
    {
        "id" : 53,
        "producto" : "Remera",
        "nombre" : "Remera estampada",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Remera_blanca_logo.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 5100,
    },
    {
        "id" : 54,
        "producto" : "Remera",
        "nombre" : "Remera blanca",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Remera_blanca_rosa.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 5000,
    },
    {
        "id" : 55,
        "producto" : "Remera",
        "nombre" : "Remera corta",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Remera_blanca_tigre.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 5000,
    },
    {
        "id" : 56,
        "producto" : "Remera",
        "nombre" : "Remera 3 colores",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Remera_tricolor.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 5700,
    },
    {
        "id" : 57,
        "producto" : "Remera",
        "nombre" : "Remera verde",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Remera_verde.jpg"],
        "marca" : "Style Drip",
        "talles" : "xs,s,m,l,xl",
        "precio" : 5900,
    },
    {
        "id" : 58,
        "producto" : "Remera",
        "nombre" : "Top believe",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Top_amarillo.jpg"],
        "marca" : "Style Drip",
        "talles" : "xs,s,m,l,xl",
        "precio" : 6000,
    },
    {
        "id" : 59,
        "producto" : "Remera",
        "nombre" : "Top amarillo rallado",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Top_amarillo_rallado.jpg"],
        "marca" : "Style Drip",
        "talles" : "xs,s,m,l,xl",
        "precio" : 6000,
    },
    {
        "id" : 60,
        "producto" : "Remera",
        "nombre" : "Top blanco con negro",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Top_blanco_mangas_negras.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 6500,
    },
    {
        "id" : 61,
        "producto" : "Remera",
        "nombre" : "Top blanco con rayas",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Top_blanco_mangas_rayas.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 6500,
    },
    {
        "id" : 62,
        "producto" : "Remera",
        "nombre" : "Top blanco mangas violeta",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Top_blanco_mangas_violeta.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 5600,
    },
    {
        "id" : 63,
        "producto" : "Remera",
        "nombre" : "Top 3 colores",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Top_blanco_negro.jpg"],
        "marca" : "Style Drip",
        "talles" : "xs,s,m,l,xl",
        "precio" : 6700,
    },
    {
        "id" : 64,
        "producto" : "Remera",
        "nombre" : "Top gris",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Top_gris.jpg"],
        "marca" : "Style Drip",
        "talles" : "xs,s,m,l,xl",
        "precio" : 6200,
    },
    {
        "id" : 65,
        "producto" : "Remera",
        "nombre" : "Top gris",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Top_gris_negro.jpg"],
        "marca" : "Paris",
        "talles" : "xs,s,m,l,xl",
        "precio" : 6000,
    },
    {
        "id" : 66,
        "producto" : "Remera",
        "nombre" : "Top manga larga",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Top_manga_larga.jpg"],
        "marca" : "Paris",
        "talles" : "xs,s,m,l,xl",
        "precio" : 7000,
    },
    {
        "id" : 67,
        "producto" : "Remera",
        "nombre" : "Top negro",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Top_negro.jpg"],
        "marca" : "Style Drip",
        "talles" : "xs,s,m,l,xl",
        "precio" : 6000,
    },
    {
        "id" : 68,
        "producto" : "Remera",
        "nombre" : "Top transparente",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Top_transparente.jpg"],
        "marca" : "Style Drip",
        "talles" : "xs,s,m,l,xl",
        "precio" : 6300,
    },
    {
        "id" : 69,
        "producto" : "Remera",
        "nombre" : "Top verde",
        "foto" : ["../asset/Productos/Mujer-prod/Remeras/Top_verde_militar.jpg"],
        "marca" : "Style Drip",
        "talles" : "xs,s,m,l,xl",
        "precio" : 6700,
    },
    // SHOTS
    {
        "id" : 70,
        "producto" : "Short",
        "nombre" : "Short liso",
        "foto" : ["../asset/Productos/Mujer-prod/Shorts/Short_rosa.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 4500,
    },
    {
        "id" : 71,
        "producto" : "Short",
        "nombre" : "Short jean",
        "foto" : ["../asset/Productos/Mujer-prod/Shorts/Short_beige.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 4700,
    },
    {
        "id" : 72,
        "producto" : "Short",
        "nombre" : "Short camuflado",
        "foto" : ["../asset/Productos/Mujer-prod/Shorts/Short_camuflaje.jpg"],
        "marca" : "Style Drip",
        "talles" : "xs,s,m,l,xl",
        "precio" : 4500,
    },
    {
        "id" : 73,
        "producto" : "Short",
        "nombre" : "Short cuadriculado",
        "foto" : ["../asset/Productos/Mujer-prod/Shorts/Short_cuadriculado.jpg"],
        "marca" : "Style Drip",
        "talles" : "xs,s,m,l,xl",
        "precio" : 4800,
    },
    {
        "id" : 74,
        "producto" : "Short",
        "nombre" : "Short deportivo",
        "foto" : ["../asset/Productos/Mujer-prod/Shorts/Short_deportivo.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 4300,
    },
    {
        "id" : 75,
        "producto" : "Short",
        "nombre" : "Short deportivo",
        "foto" : ["../asset/Productos/Mujer-prod/Shorts/Short_deportivo_negro.jpg"],
        "marca" : "addidas",
        "talles" : "xs,s,m,l,xl",
        "precio" : 6000,
    },
    {
        "id" : 76,
        "producto" : "Short",
        "nombre" : "Short jean ancho",
        "foto" : ["../asset/Productos/Mujer-prod/Shorts/Short_jean_ancho.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 5000,
    },
    {
        "id" : 77,
        "producto" : "Short",
        "nombre" : "Short jean",
        "foto" : ["../asset/Productos/Mujer-prod/Shorts/Short_jean_claro.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 5000,
    },
    {
        "id" : 78,
        "producto" : "Short",
        "nombre" : "Short jean",
        "foto" : ["../asset/Productos/Mujer-prod/Shorts/Short_jean_negro.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 5000,
    },
    {
        "id" : 79,
        "producto" : "Short",
        "nombre" : "Short jean",
        "foto" : ["../asset/Productos/Mujer-prod/Shorts/Short_jean_negro.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 5000,
    },
    {
        "id" : 80,
        "producto" : "Short",
        "nombre" : "Short liso",
        "foto" : ["../asset/Productos/Mujer-prod/Shorts/Short_marron.jpg"],
        "marca" : "Style Drip",
        "talles" : "xs,s,m,l,xl",
        "precio" : 4500,
    },
    {
        "id" : 81,
        "producto" : "Short",
        "nombre" : "Short liso",
        "foto" : ["../asset/Productos/Mujer-prod/Shorts/Short_negro.jpg"],
        "marca" : "Style Drip",
        "talles" : "xs,s,m,l,xl",
        "precio" : 4700,
    },
    {
        "id" : 82,
        "producto" : "Short",
        "nombre" : "Short jean",
        "foto" : ["../asset/Productos/Mujer-prod/Shorts/Short_rojo.jpg"],
        "marca" : "Moda SR",
        "talles" : "xs,s,m,l,xl",
        "precio" : 4900,
    },
    {
        "id" : 83,
        "producto" : "Short",
        "nombre" : "Short ancho",
        "foto" : ["../asset/Productos/Mujer-prod/Shorts/Short_verde_claro.jpg"],
        "marca" : "Style Drip",
        "talles" : "xs,s,m,l,xl",
        "precio" : 5100,
    },
    {
        "id" : 84,
        "producto" : "Short",
        "nombre" : "Short jean",
        "foto" : ["../asset/Productos/Mujer-prod/Shorts/Short_verde_musgo.jpg"],
        "marca" : "Style Drip",
        "talles" : "xs,s,m,l,xl",
        "precio" : 4700,
    },
    {
        "id" : 85,
        "producto" : "Short",
        "nombre" : "Short ancho",
        "foto" : ["../asset/Productos/Mujer-prod/Shorts/Short_verde_suelto.jpg"],
        "marca" : "Style Drip",
        "talles" : "xs,s,m,l,xl",
        "precio" : 4700,
    },
]
const productoshombre = [
    // BUZOS
    {
        "id" : 86,
        "producto" : "Buzo H",
        "nombre" : "Buzo 2 colores",
        "foto" : ["../asset/Productos/Hombres-prod/Buzos/Buzo_amarillo_negro.jpg"],
        "marca" : "Years",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 10000,
    },
    {
        "id" : 87,
        "producto" : "Buzo H",
        "nombre" : "Buzo estampado",
        "foto" : ["../asset/Productos/Hombres-prod/Buzos/Buzo_amarillo_negro_con_detalles.jpg"],
        "marca" : "Years",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 11000,
    },
    {
        "id" : 88,
        "producto" : "Buzo H",
        "nombre" : "Buzo 2 colores",
        "foto" : ["../asset/Productos/Hombres-prod/Buzos/Buzo_beige_claro_negro.jpg"],
        "marca" : "Gap",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 10000,
    },
    {
        "id" : 89,
        "producto" : "Buzo H",
        "nombre" : "Buzo 3 colores",
        "foto" : ["../asset/Productos/Hombres-prod/Buzos/Buzo_beige_degrade.jpg"],
        "marca" : "Nasa",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 12000,
    },
    {
        "id" : 90,
        "producto" : "Buzo H",
        "nombre" : "Buzo 3 colores",
        "foto" : ["../asset/Productos/Hombres-prod/Buzos/Buzo_blanco_beige_negro.jpg"],
        "marca" : "Nasa",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 13000,
    },
    {
        "id" : 91,
        "producto" : "Buzo H",
        "nombre" : "Buzo 2 colores",
        "foto" : ["../asset/Productos/Hombres-prod/Buzos/Buzo_blanco_celeste.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 12000,
    },
    {
        "id" : 92,
        "producto" : "Buzo H",
        "nombre" : "Buzo estampada",
        "foto" : ["../asset/Productos/Hombres-prod/Buzos/Buzo_blanco_detalles_gris.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 13000,
    },
    {
        "id" : 93,
        "producto" : "Buzo H",
        "nombre" : "Buzo 3 colores",
        "foto" : ["../asset/Productos/Hombres-prod/Buzos/Buzo_gris_blanco_verde.jpg"],
        "marca" : "Years",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 10000,
    },
    {
        "id" : 94,
        "producto" : "Buzo H",
        "nombre" : "Buzo naranja",
        "foto" : ["../asset/Productos/Hombres-prod/Buzos/Buzo_naranja_negro.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 12000,
    },
    {
        "id" : 95,
        "producto" : "Buzo H",
        "nombre" : "Buzo estampado",
        "foto" : ["../asset/Productos/Hombres-prod/Buzos/Buzo_negro_A.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 14000,
    },
    {
        "id" : 96,
        "producto" : "Buzo H",
        "nombre" : "Buzo negro",
        "foto" : ["../asset/Productos/Hombres-prod/Buzos/Buzo_negro_beige.jpg"],
        "marca" : "Nasa",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 11000,
    },
    {
        "id" : 97,
        "producto" : "Buzo H",
        "nombre" : "Buzo 3 colores",
        "foto" : ["../asset/Productos/Hombres-prod/Buzos/Buzo_negro_blanco_gris.jpg"],
        "marca" : "Nasa",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 12000,
    },
    {
        "id" : 98,
        "producto" : "Buzo H",
        "nombre" : "Buzo estampado",
        "foto" : ["../asset/Productos/Hombres-prod/Buzos/Buzo_negro_bordo.jpg"],
        "marca" : "Stard",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 12000,
    },
    {
        "id" : 99,
        "producto" : "Buzo H",
        "nombre" : "Buzo 2 colores",
        "foto" : ["../asset/Productos/Hombres-prod/Buzos/Buzo_verde_negro.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 10000,
    },
    // CAMPERAS
    {
        "id" : 100,
        "producto" : "Campera H",
        "nombre" : "Campera Blanca",
        "foto" : ["../asset/Productos/Hombres-prod/Camperas/Campera_blanca.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 17000,
    },
    {
        "id" : 101,
        "producto" : "Campera H",
        "nombre" : "Campera bordo",
        "foto" : ["../asset/Productos/Hombres-prod/Camperas/Campera_cordero_bordo.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 18000,
    },
    {
        "id" : 102,
        "producto" : "Campera H",
        "nombre" : "Campera cuero",
        "foto" : ["../asset/Productos/Hombres-prod/Camperas/Campera_cuero_negra.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 20000,
    },
    {
        "id" : 103,
        "producto" : "Campera H",
        "nombre" : "Campera cuero",
        "foto" : ["../asset/Productos/Hombres-prod/Camperas/Campera_cuero_verde.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 19000,
    },
    {
        "id" : 104,
        "producto" : "Campera H",
        "nombre" : "Campera jean",
        "foto" : ["../asset/Productos/Hombres-prod/Camperas/Campera_jean.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 16000,
    },
    {
        "id" : 105,
        "producto" : "Campera H",
        "nombre" : "Campera algodon",
        "foto" : ["../asset/Productos/Hombres-prod/Camperas/Campera_negra.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 14000,
    },
    {
        "id" : 106,
        "producto" : "Campera H",
        "nombre" : "Campera algodon",
        "foto" : ["../asset/Productos/Hombres-prod/Camperas/Campera_negra_2.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 14000,
    },
    {
        "id" : 107,
        "producto" : "Campera H",
        "nombre" : "Campera algodon",
        "foto" : ["../asset/Productos/Hombres-prod/Camperas/Campera_roja.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 15000,
    },
    {
        "id" : 108,
        "producto" : "Campera H",
        "nombre" : "Campera algodon",
        "foto" : ["../asset/Productos/Hombres-prod/Camperas/Campera_verde.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 11000,
    },
    // GORRAS
    {
        "id" : 109,
        "producto" : "Gorra H",
        "nombre" : "Gorra estampada",
        "foto" : ["../asset/Productos/Hombres-prod/Gorras/Gorra_azul_palmera.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 3000,
    },
    {
        "id" : 110,
        "producto" : "Gorra H",
        "nombre" : "Gorra con imagen",
        "foto" : ["../asset/Productos/Hombres-prod/Gorras/Gorra_beige_tigre.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 3100,
    },
    {
        "id" : 111,
        "producto" : "Gorra H",
        "nombre" : "Gorra",
        "foto" : ["../asset/Productos/Hombres-prod/Gorras/Gorra_blanca.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 3100,
    },
    {
        "id" : 112,
        "producto" : "Gorra H",
        "nombre" : "Gorra militar",
        "foto" : ["../asset/Productos/Hombres-prod/Gorras/Gorra_camuflaje.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 3200,
    },
    {
        "id" : 113,
        "producto" : "Gorra H",
        "nombre" : "Gorra jean",
        "foto" : ["../asset/Productos/Hombres-prod/Gorras/Gorra_clasica_jean.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 2400,
    },
    {
        "id" : 114,
        "producto" : "Gorra H",
        "nombre" : "Gorra lisa",
        "foto" : ["../asset/Productos/Hombres-prod/Gorras/Gorra_gris.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 3000,
    },
    {
        "id" : 115,
        "producto" : "Gorra H",
        "nombre" : "Gorra con imagen",
        "foto" : ["../asset/Productos/Hombres-prod/Gorras/Gorra_gris_tigre.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 3200,
    },
    {
        "id" : 116,
        "producto" : "Gorra H",
        "nombre" : "Gorra con imagen",
        "foto" : ["../asset/Productos/Hombres-prod/Gorras/Gorra_marron_oso.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 3200,
    },
    {
        "id" : 117,
        "producto" : "Gorra H",
        "nombre" : "Gorra lisa",
        "foto" : ["../asset/Productos/Hombres-prod/Gorras/Gorra_negra.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 3000,
    },
    {
        "id" : 118,
        "producto" : "Gorra H",
        "nombre" : "Gorra con imagen",
        "foto" : ["../asset/Productos/Hombres-prod/Gorras/Gorra_negra_puma.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 3000,
    },
    {
        "id" : 119,
        "producto" : "Gorra H",
        "nombre" : "Gorra lisa",
        "foto" : ["../asset/Productos/Hombres-prod/Gorras/Gorra_roja.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 3100,
    },
    {
        "id" : 120,
        "producto" : "Gorra H",
        "nombre" : "Gorra con imagen",
        "foto" : ["../asset/Productos/Hombres-prod/Gorras/Gorra_serpiente.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 3200,
    },
    // PANTALONES
    {
        "id" : 121,
        "producto" : "Pantalon H",
        "nombre" : "Pantalon cargo",
        "foto" : ["../asset/Productos/Hombres-prod/Pantalones/Pantalon_beige_1.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 6200,
    },
    {
        "id" : 122,
        "producto" : "Pantalon H",
        "nombre" : "Pantalon cargo",
        "foto" : ["../asset/Productos/Hombres-prod/Pantalones/Pantalon_beige_2.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 6200,
    },
    {
        "id" : 123,
        "producto" : "Pantalon H",
        "nombre" : "Pantalon chupin",
        "foto" : ["../asset/Productos/Hombres-prod/Pantalones/Pantalon_blanco_negro.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 6000,
    },
    {
        "id" : 124,
        "producto" : "Pantalon H",
        "nombre" : "Pantalon chupin",
        "foto" : ["../asset/Productos/Hombres-prod/Pantalones/Pantalon_chupin_negro.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 6000,
    },
    {
        "id" : 125,
        "producto" : "Pantalon H",
        "nombre" : "Pantalon chupin",
        "foto" : ["../asset/Productos/Hombres-prod/Pantalones/Pantalon_gris.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 6100,
    },
    {
        "id" : 126,
        "producto" : "Pantalon H",
        "nombre" : "Pantalon cargo",
        "foto" : ["../asset/Productos/Hombres-prod/Pantalones/Pantalon_gris_claro.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5900,
    },
    {
        "id" : 127,
        "producto" : "Pantalon H",
        "nombre" : "Pantalon jean",
        "foto" : ["../asset/Productos/Hombres-prod/Pantalones/Pantalon_jean_chupin.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 6400,
    },
    {
        "id" : 128,
        "producto" : "Pantalon H",
        "nombre" : "Pantalon jean",
        "foto" : ["../asset/Productos/Hombres-prod/Pantalones/Pantalon_jean_chupin_2.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 6400,
    },
    {
        "id" : 129,
        "producto" : "Pantalon H",
        "nombre" : "Pantalon jean",
        "foto" : ["../asset/Productos/Hombres-prod/Pantalones/Pantalon_jean_suelto.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 6700,
    },
    {
        "id" : 130,
        "producto" : "Pantalon H",
        "nombre" : "Pantalon jean",
        "foto" : ["../asset/Productos/Hombres-prod/Pantalones/Pantalon_negro.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 6200,
    },
    {
        "id" : 131,
        "producto" : "Pantalon H",
        "nombre" : "Pantalon cargo",
        "foto" : ["../asset/Productos/Hombres-prod/Pantalones/Pantalon_suelto_negro_rojo.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 6300,
    },
    {
        "id" : 132,
        "producto" : "Pantalon H",
        "nombre" : "Pantalon cargo",
        "foto" : ["../asset/Productos/Hombres-prod/Pantalones/Pantalon_verde.jpg"],
        "marca" : "Moda SR",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 6400,
    },
    // REMERAS
    {
        "id" : 133,
        "producto" : "Remera H",
        "nombre" : "Remera lisa",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_azul_mangas_negras.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5100,
    },
    {
        "id" : 134,
        "producto" : "Remera H",
        "nombre" : "Remera 2 colores",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_beige_negra.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5200,
    },
    {
        "id" : 135,
        "producto" : "Remera H",
        "nombre" : "Remera lisa",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_beige_oscura.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5000,
    },
    {
        "id" : 136,
        "producto" : "Remera H",
        "nombre" : "Remera estampa",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_beige_oso.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5200,
    },
    {
        "id" : 137,
        "producto" : "Remera H",
        "nombre" : "Remera estampada",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_beige_palmera.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5400,
    },
    {
        "id" : 138,
        "producto" : "Remera H",
        "nombre" : "Remera estampada",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_blanca_estampada.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5200,
    },
    {
        "id" : 139,
        "producto" : "Remera H",
        "nombre" : "Remera lisa",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_blanca_linea_gris.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5300,
    },
    {
        "id" : 140,
        "producto" : "Remera H",
        "nombre" : "Remera estampada",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_blanca_linea_negra.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5100,
    },
    {
        "id" : 141,
        "producto" : "Remera H",
        "nombre" : "Remera estampada",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_blanca_manchada.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5500,
    },
    {
        "id" : 142,
        "producto" : "Remera H",
        "nombre" : "Remera detalles",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_blanca_manga_negra.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5200,
    },
    {
        "id" : 143,
        "producto" : "Remera H",
        "nombre" : "Remera lisa",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_bordo.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5400,
    },
    {
        "id" : 144,
        "producto" : "Remera H",
        "nombre" : "Remera estampada",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_celeste.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5400,
    },
    {
        "id" : 145,
        "producto" : "Remera H",
        "nombre" : "Remera detalles",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_clara.jfif"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5500,
    },
    {
        "id" : 146,
        "producto" : "Remera H",
        "nombre" : "Remera detalle",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_crema.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5400,
    },
    {
        "id" : 147,
        "producto" : "Remera H",
        "nombre" : "Remera detalle",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_gris.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5200,
    },
    {
        "id" : 148,
        "producto" : "Remera H",
        "nombre" : "Remera detalle",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_gris_claro.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5400,
    },
    {
        "id" : 149,
        "producto" : "Remera H",
        "nombre" : "Remera Nasa",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_negra.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5100,
    },
    {
        "id" : 150,
        "producto" : "Remera H",
        "nombre" : "Remera 2 colores",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_negra_blanca.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5200,
    },
    {
        "id" : 151,
        "producto" : "Remera H",
        "nombre" : "Remera estampada",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_oso_beige.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5400,
    },
    {
        "id" : 152,
        "producto" : "Remera H",
        "nombre" : "Remera lisa",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_verde_claro.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5100,
    },
    {
        "id" : 153,
        "producto" : "Remera H",
        "nombre" : "Remera detalle",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_verde_militar.png"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5100,
    },
    {
        "id" : 154,
        "producto" : "Remera H",
        "nombre" : "Remera lisa",
        "foto" : ["../asset/Productos/Hombres-prod/Remeras/Remera_verde_oscuro.jpg"],
        "marca" : "Style Drip",
        "talles" : "s,m,l,xl,xxl",
        "precio" : 5000,
    },
]